version: '3.7'

services:

  dev-mode:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/node/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
    